insert into product (id, name, price, category, stock, isdangerous) values (1, 'Chicken - Whole Fryers', 384, 'Tools', 54, true);
insert into product (id, name, price, category, stock, isdangerous) values (2, 'Flower - Leather Leaf Fern', 135, 'Jewelry', 11, true);
insert into product (id, name, price, category, stock, isdangerous) values (3, 'Mace', 946, 'Outdoors', 39, true);
insert into product (id, name, price, category, stock, isdangerous) values (4, 'Higashimaru Usukuchi Soy', 483, 'Industrial', 91, true);
insert into product (id, name, price, category, stock, isdangerous) values (5, 'Island Oasis - Banana Daiquiri', 276, 'Games', 99, false);
insert into product (id, name, price, category, stock, isdangerous) values (6, 'Lettuce - Frisee', 804, 'Jewelry', 41, false);
insert into product (id, name, price, category, stock, isdangerous) values (7, 'Spoon - Soup, Plastic', 337, 'Books', 65, false);
insert into product (id, name, price, category, stock, isdangerous) values (8, 'Rum - White, Gg White', 753, 'Electronics', 100, true);
insert into product (id, name, price, category, stock, isdangerous) values (9, 'Lobster - Cooked', 243, 'Garden', 21, false);
insert into product (id, name, price, category, stock, isdangerous) values (10, 'Cookie Dough - Chocolate Chip', 827, 'Movies', 55, true);
insert into product (id, name, price, category, stock, isdangerous) values (11, 'Cleaner - Lime Away', 52, 'Outdoors', 57, false);
insert into product (id, name, price, category, stock, isdangerous) values (12, 'Juice - Propel Sport', 366, 'Clothing', 22, true);
insert into product (id, name, price, category, stock, isdangerous) values (13, 'Thermometer Digital', 592, 'Books', 90, false);
insert into product (id, name, price, category, stock, isdangerous) values (14, 'Wine - Lou Black Shiraz', 960, 'Movies', 57, false);
insert into product (id, name, price, category, stock, isdangerous) values (15, 'Tomato - Plum With Basil', 720, 'Jewelry', 85, true);
insert into product (id, name, price, category, stock, isdangerous) values (16, 'Tortillas - Flour, 10', 649, 'Automotive', 37, true);
insert into product (id, name, price, category, stock, isdangerous) values (17, 'Venison - Ground', 962, 'Health', 33, false);
insert into product (id, name, price, category, stock, isdangerous) values (18, 'Quail - Jumbo Boneless', 500, 'Industrial', 75, true);
insert into product (id, name, price, category, stock, isdangerous) values (19, 'Sugar - Palm', 252, 'Kids', 59, false);
insert into product (id, name, price, category, stock, isdangerous) values (20, 'Tandoori Curry Paste', 576, 'Home', 41, false);
insert into product (id, name, price, category, stock, isdangerous) values (21, 'Pickerel - Fillets', 537, 'Baby', 61, false);
insert into product (id, name, price, category, stock, isdangerous) values (22, 'Durian Fruit', 653, 'Sports', 53, true);
insert into product (id, name, price, category, stock, isdangerous) values (23, 'Kirsch - Schloss', 995, 'Shoes', 46, false);
insert into product (id, name, price, category, stock, isdangerous) values (24, 'Bar Bran Honey Nut', 423, 'Home', 52, false);
insert into product (id, name, price, category, stock, isdangerous) values (25, 'Pumpkin', 972, 'Books', 86, false);
insert into product (id, name, price, category, stock, isdangerous) values (26, 'Wine - Rioja Campo Viejo', 472, 'Electronics', 12, true);
insert into product (id, name, price, category, stock, isdangerous) values (27, 'Jagermeister', 475, 'Movies', 82, false);
insert into product (id, name, price, category, stock, isdangerous) values (28, 'Sachet', 476, 'Sports', 65, false);
insert into product (id, name, price, category, stock, isdangerous) values (29, 'Sprouts - Alfalfa', 310, 'Sports', 48, true);
insert into product (id, name, price, category, stock, isdangerous) values (30, 'Lemon Balm - Fresh', 568, 'Industrial', 86, false);
insert into product (id, name, price, category, stock, isdangerous) values (31, 'Oil - Shortening - All - Purpose', 62, 'Clothing', 98, false);
insert into product (id, name, price, category, stock, isdangerous) values (32, 'Oranges', 557, 'Industrial', 85, false);
insert into product (id, name, price, category, stock, isdangerous) values (33, 'Ecolab Digiclean Mild Fm', 779, 'Home', 29, true);
insert into product (id, name, price, category, stock, isdangerous) values (34, 'Pasta - Spaghetti, Dry', 346, 'Outdoors', 60, false);
insert into product (id, name, price, category, stock, isdangerous) values (35, 'Olive - Spread Tapenade', 759, 'Movies', 80, true);
insert into product (id, name, price, category, stock, isdangerous) values (36, 'Wine - Prosecco Valdobiaddene', 574, 'Computers', 100, false);
insert into product (id, name, price, category, stock, isdangerous) values (37, 'Turnip - White', 346, 'Computers', 47, false);
insert into product (id, name, price, category, stock, isdangerous) values (38, 'Wine - Fume Blanc Fetzer', 796, 'Movies', 50, true);
insert into product (id, name, price, category, stock, isdangerous) values (39, 'Mortadella', 793, 'Games', 9, false);
insert into product (id, name, price, category, stock, isdangerous) values (40, 'Trout - Rainbow, Frozen', 300, 'Health', 34, true);
insert into product (id, name, price, category, stock, isdangerous) values (41, 'Squash - Pepper', 436, 'Outdoors', 37, true);
insert into product (id, name, price, category, stock, isdangerous) values (42, 'Cotton Wet Mop 16 Oz', 644, 'Kids', 57, false);
insert into product (id, name, price, category, stock, isdangerous) values (43, 'Creme De Cacao Mcguines', 832, 'Kids', 9, false);
insert into product (id, name, price, category, stock, isdangerous) values (44, 'Towels - Paper / Kraft', 159, 'Outdoors', 56, false);
insert into product (id, name, price, category, stock, isdangerous) values (45, 'Creme De Menth - White', 870, 'Clothing', 100, true);
insert into product (id, name, price, category, stock, isdangerous) values (46, 'Tea - Mint', 372, 'Games', 78, false);
insert into product (id, name, price, category, stock, isdangerous) values (47, 'Chinese Foods - Chicken Wing', 710, 'Health', 2, false);
insert into product (id, name, price, category, stock, isdangerous) values (48, 'Puree - Strawberry', 769, 'Movies', 91, true);
insert into product (id, name, price, category, stock, isdangerous) values (49, 'Chocolate Bar - Oh Henry', 854, 'Toys', 53, true);
insert into product (id, name, price, category, stock, isdangerous) values (50, 'Laundry - Bag Cloth', 925, 'Electronics', 30, true);
insert into product (id, name, price, category, stock, isdangerous) values (51, 'Dried Peach', 434, 'Games', 36, true);
insert into product (id, name, price, category, stock, isdangerous) values (52, 'Ecolab Digiclean Mild Fm', 718, 'Health', 31, false);
insert into product (id, name, price, category, stock, isdangerous) values (53, 'White Fish - Filets', 207, 'Music', 65, true);
insert into product (id, name, price, category, stock, isdangerous) values (54, 'Oil - Hazelnut', 876, 'Tools', 74, true);
insert into product (id, name, price, category, stock, isdangerous) values (55, 'Corn - Cream, Canned', 615, 'Computers', 70, false);
insert into product (id, name, price, category, stock, isdangerous) values (56, 'Soup - Campbells - Tomato', 412, 'Clothing', 67, false);
insert into product (id, name, price, category, stock, isdangerous) values (57, 'Oven Mitt - 13 Inch', 800, 'Electronics', 47, true);
insert into product (id, name, price, category, stock, isdangerous) values (58, 'Soup Knorr Chili With Beans', 259, 'Books', 2, true);
insert into product (id, name, price, category, stock, isdangerous) values (59, 'Veal - Kidney', 770, 'Jewelry', 56, false);
insert into product (id, name, price, category, stock, isdangerous) values (60, 'Beef Ground Medium', 630, 'Kids', 51, false);
insert into product (id, name, price, category, stock, isdangerous) values (61, 'Beans - Soya Bean', 374, 'Movies', 72, false);
insert into product (id, name, price, category, stock, isdangerous) values (62, 'Eggs - Extra Large', 889, 'Outdoors', 36, true);
insert into product (id, name, price, category, stock, isdangerous) values (63, 'Mountain Dew', 670, 'Music', 24, false);
insert into product (id, name, price, category, stock, isdangerous) values (64, 'Chicken - Ground', 113, 'Health', 23, false);
insert into product (id, name, price, category, stock, isdangerous) values (65, 'Garam Marsala', 148, 'Outdoors', 68, true);
insert into product (id, name, price, category, stock, isdangerous) values (66, 'Cheese - Camembert', 479, 'Toys', 39, true);
insert into product (id, name, price, category, stock, isdangerous) values (67, 'Octopus - Baby, Cleaned', 547, 'Health', 36, false);
insert into product (id, name, price, category, stock, isdangerous) values (68, 'Juice - Apple 284ml', 893, 'Baby', 7, false);
insert into product (id, name, price, category, stock, isdangerous) values (69, 'Veal - Provimi Inside', 955, 'Shoes', 42, false);
insert into product (id, name, price, category, stock, isdangerous) values (70, 'Wine - Domaine Boyar Royal', 76, 'Sports', 30, false);
insert into product (id, name, price, category, stock, isdangerous) values (71, 'Bag - Clear 7 Lb', 254, 'Books', 1, true);
insert into product (id, name, price, category, stock, isdangerous) values (72, 'Stock - Beef, Brown', 711, 'Home', 15, false);
insert into product (id, name, price, category, stock, isdangerous) values (73, 'Pork - Bones', 973, 'Music', 33, true);
insert into product (id, name, price, category, stock, isdangerous) values (74, 'Mix - Cocktail Strawberry Daiquiri', 163, 'Baby', 6, true);
insert into product (id, name, price, category, stock, isdangerous) values (75, 'Mushroom - White Button', 130, 'Computers', 55, false);
insert into product (id, name, price, category, stock, isdangerous) values (76, 'Butter - Unsalted', 53, 'Grocery', 4, false);
insert into product (id, name, price, category, stock, isdangerous) values (77, 'Sausage - Chorizo', 855, 'Grocery', 80, false);
insert into product (id, name, price, category, stock, isdangerous) values (78, 'Apple - Granny Smith', 796, 'Toys', 2, false);
insert into product (id, name, price, category, stock, isdangerous) values (79, 'Beer - Camerons Auburn', 109, 'Tools', 15, true);
insert into product (id, name, price, category, stock, isdangerous) values (80, 'Beer - Sleeman Fine Porter', 693, 'Home', 55, false);
insert into product (id, name, price, category, stock, isdangerous) values (81, 'Beer - Labatt Blue', 274, 'Shoes', 21, true);
insert into product (id, name, price, category, stock, isdangerous) values (82, 'Mushroom - Oyster, Fresh', 108, 'Home', 87, false);
insert into product (id, name, price, category, stock, isdangerous) values (83, 'Quail - Eggs, Fresh', 90, 'Shoes', 7, false);
insert into product (id, name, price, category, stock, isdangerous) values (84, 'Bread Base - Goodhearth', 320, 'Baby', 77, true);
insert into product (id, name, price, category, stock, isdangerous) values (85, 'Melon - Cantaloupe', 260, 'Baby', 66, false);
insert into product (id, name, price, category, stock, isdangerous) values (86, 'Cheese - Gouda Smoked', 809, 'Garden', 82, false);
insert into product (id, name, price, category, stock, isdangerous) values (87, 'Wine - Alicanca Vinho Verde', 729, 'Shoes', 22, true);
insert into product (id, name, price, category, stock, isdangerous) values (88, 'Rice Paper', 358, 'Sports', 14, false);
insert into product (id, name, price, category, stock, isdangerous) values (89, 'Apple - Custard', 404, 'Toys', 27, false);
insert into product (id, name, price, category, stock, isdangerous) values (90, 'Syrup - Chocolate', 980, 'Health', 98, false);
insert into product (id, name, price, category, stock, isdangerous) values (91, 'Truffle - Peelings', 501, 'Music', 79, false);
insert into product (id, name, price, category, stock, isdangerous) values (92, 'Fenngreek Seed', 834, 'Computers', 25, true);
insert into product (id, name, price, category, stock, isdangerous) values (93, 'Chocolate - White', 362, 'Games', 7, false);
insert into product (id, name, price, category, stock, isdangerous) values (94, 'Tobasco Sauce', 409, 'Games', 36, true);
insert into product (id, name, price, category, stock, isdangerous) values (95, 'Wine - Ruffino Chianti', 216, 'Games', 24, true);
insert into product (id, name, price, category, stock, isdangerous) values (96, 'Syrup - Chocolate', 330, 'Toys', 99, true);
insert into product (id, name, price, category, stock, isdangerous) values (97, 'Wine - White Cab Sauv.on', 515, 'Computers', 41, true);
insert into product (id, name, price, category, stock, isdangerous) values (98, 'Quail Eggs - Canned', 106, 'Outdoors', 43, true);
insert into product (id, name, price, category, stock, isdangerous) values (99, 'Placemat - Scallop, White', 502, 'Electronics', 58, true);
insert into product (id, name, price, category, stock, isdangerous) values (100, 'Ice Cream - Vanilla', 799, 'Outdoors', 22, false);
insert into product (id, name, price, category, stock, isdangerous) values (101, 'Island Oasis - Banana Daiquiri', 174, 'Automotive', 62, false);
insert into product (id, name, price, category, stock, isdangerous) values (102, 'External Supplier', 851, 'Home', 29, true);
insert into product (id, name, price, category, stock, isdangerous) values (103, 'Bag - Bread, White, Plain', 61, 'Tools', 66, false);
insert into product (id, name, price, category, stock, isdangerous) values (104, 'Turkey Leg With Drum And Thigh', 81, 'Movies', 81, true);
insert into product (id, name, price, category, stock, isdangerous) values (105, 'Lamb - Racks, Frenched', 943, 'Electronics', 81, true);
insert into product (id, name, price, category, stock, isdangerous) values (106, 'Scallops - Live In Shell', 963, 'Home', 50, true);
insert into product (id, name, price, category, stock, isdangerous) values (107, 'Cactus Pads', 217, 'Kids', 30, true);
insert into product (id, name, price, category, stock, isdangerous) values (108, 'Nantuket Peach Orange', 721, 'Toys', 51, true);
insert into product (id, name, price, category, stock, isdangerous) values (109, 'Cheese - St. Paulin', 597, 'Baby', 59, false);
insert into product (id, name, price, category, stock, isdangerous) values (110, 'Flour - So Mix Cake White', 972, 'Home', 69, false);
insert into product (id, name, price, category, stock, isdangerous) values (111, 'Parsley - Fresh', 178, 'Grocery', 25, true);
insert into product (id, name, price, category, stock, isdangerous) values (112, 'Water - Mineral, Carbonated', 680, 'Jewelry', 65, true);
insert into product (id, name, price, category, stock, isdangerous) values (113, 'Stock - Chicken, White', 106, 'Clothing', 6, true);
insert into product (id, name, price, category, stock, isdangerous) values (114, 'Bandage - Fexible 1x3', 863, 'Kids', 94, false);
insert into product (id, name, price, category, stock, isdangerous) values (115, 'Sauce - Oyster', 772, 'Outdoors', 71, true);
insert into product (id, name, price, category, stock, isdangerous) values (116, 'Croissant, Raw - Mini', 380, 'Toys', 100, true);
insert into product (id, name, price, category, stock, isdangerous) values (117, 'Cumin - Ground', 760, 'Computers', 83, true);
insert into product (id, name, price, category, stock, isdangerous) values (118, 'Lemon Grass', 144, 'Outdoors', 78, false);
insert into product (id, name, price, category, stock, isdangerous) values (119, 'Galliano', 978, 'Garden', 84, true);
insert into product (id, name, price, category, stock, isdangerous) values (120, 'Shrimp, Dried, Small / Lb', 389, 'Shoes', 43, true);
insert into product (id, name, price, category, stock, isdangerous) values (121, 'Cheese - Roquefort Pappillon', 349, 'Baby', 45, true);
insert into product (id, name, price, category, stock, isdangerous) values (122, 'Soup - Verve - Chipotle Chicken', 926, 'Garden', 48, false);
insert into product (id, name, price, category, stock, isdangerous) values (123, 'Lettuce - Arugula', 258, 'Sports', 60, false);
insert into product (id, name, price, category, stock, isdangerous) values (124, 'Goat - Leg', 697, 'Books', 33, false);
insert into product (id, name, price, category, stock, isdangerous) values (125, 'Icecream - Dstk Strw Chseck', 469, 'Outdoors', 91, false);
insert into product (id, name, price, category, stock, isdangerous) values (126, 'Sugar - Brown, Individual', 138, 'Books', 1, true);
insert into product (id, name, price, category, stock, isdangerous) values (127, 'Spinach - Baby', 441, 'Toys', 5, false);
insert into product (id, name, price, category, stock, isdangerous) values (128, 'Wine - Masi Valpolocell', 456, 'Kids', 12, true);
insert into product (id, name, price, category, stock, isdangerous) values (129, 'Flour Dark Rye', 605, 'Industrial', 62, false);
insert into product (id, name, price, category, stock, isdangerous) values (130, 'Ice Cream - Vanilla', 481, 'Music', 28, true);
insert into product (id, name, price, category, stock, isdangerous) values (131, 'Puree - Mango', 112, 'Computers', 78, true);
insert into product (id, name, price, category, stock, isdangerous) values (132, 'Steamers White', 227, 'Games', 44, false);
insert into product (id, name, price, category, stock, isdangerous) values (133, 'Napkin White', 114, 'Clothing', 53, true);
insert into product (id, name, price, category, stock, isdangerous) values (134, 'Tamarind Paste', 944, 'Kids', 75, false);
insert into product (id, name, price, category, stock, isdangerous) values (135, 'Container - Clear 32 Oz', 138, 'Electronics', 30, false);
insert into product (id, name, price, category, stock, isdangerous) values (136, 'Lamb - Whole Head Off', 32, 'Music', 39, true);
insert into product (id, name, price, category, stock, isdangerous) values (137, 'Island Oasis - Cappucino Mix', 56, 'Garden', 60, false);
insert into product (id, name, price, category, stock, isdangerous) values (138, 'Venison - Liver', 485, 'Health', 71, false);
insert into product (id, name, price, category, stock, isdangerous) values (139, 'Soup - Campbells Beef Strogonoff', 879, 'Grocery', 10, true);
insert into product (id, name, price, category, stock, isdangerous) values (140, 'Pan Grease', 499, 'Sports', 76, true);
insert into product (id, name, price, category, stock, isdangerous) values (141, 'Tia Maria', 587, 'Automotive', 24, false);
insert into product (id, name, price, category, stock, isdangerous) values (142, 'Pork - Tenderloin, Fresh', 205, 'Garden', 9, true);
insert into product (id, name, price, category, stock, isdangerous) values (143, 'Sauce - Caesar Dressing', 807, 'Sports', 20, true);
insert into product (id, name, price, category, stock, isdangerous) values (144, 'Tomato - Plum With Basil', 316, 'Garden', 29, true);
insert into product (id, name, price, category, stock, isdangerous) values (145, 'Coffee - Decafenated', 707, 'Baby', 60, false);
insert into product (id, name, price, category, stock, isdangerous) values (146, 'Sponge Cake Mix - Vanilla', 321, 'Health', 46, false);
insert into product (id, name, price, category, stock, isdangerous) values (147, 'Trout - Rainbow, Fresh', 414, 'Electronics', 37, true);
insert into product (id, name, price, category, stock, isdangerous) values (148, 'Sauce - Alfredo', 470, 'Electronics', 23, true);
insert into product (id, name, price, category, stock, isdangerous) values (149, 'Lid Tray - 12in Dome', 682, 'Health', 6, false);
insert into product (id, name, price, category, stock, isdangerous) values (150, 'Tart - Pecan Butter Squares', 309, 'Toys', 22, true);
insert into product (id, name, price, category, stock, isdangerous) values (151, 'Aspic - Amber', 863, 'Garden', 43, false);
insert into product (id, name, price, category, stock, isdangerous) values (152, 'Cherries - Maraschino,jar', 464, 'Toys', 31, true);
insert into product (id, name, price, category, stock, isdangerous) values (153, 'Lamb - Ground', 484, 'Automotive', 87, false);
insert into product (id, name, price, category, stock, isdangerous) values (154, 'Sauce - Soy Low Sodium - 3.87l', 381, 'Toys', 74, false);
insert into product (id, name, price, category, stock, isdangerous) values (155, 'Cranberries - Fresh', 984, 'Computers', 16, true);
insert into product (id, name, price, category, stock, isdangerous) values (156, 'Coke - Diet, 355 Ml', 950, 'Beauty', 40, false);
insert into product (id, name, price, category, stock, isdangerous) values (157, 'Crab - Claws, Snow 16 - 24', 996, 'Automotive', 23, false);
insert into product (id, name, price, category, stock, isdangerous) values (158, 'Sauce - Mint', 977, 'Automotive', 6, true);
insert into product (id, name, price, category, stock, isdangerous) values (159, 'Cardamon Ground', 232, 'Tools', 42, false);
insert into product (id, name, price, category, stock, isdangerous) values (160, 'Water - Spring Water 500ml', 694, 'Games', 8, true);
insert into product (id, name, price, category, stock, isdangerous) values (161, 'Hand Towel', 416, 'Baby', 6, true);
insert into product (id, name, price, category, stock, isdangerous) values (162, 'Oil - Grapeseed Oil', 859, 'Automotive', 25, true);
insert into product (id, name, price, category, stock, isdangerous) values (163, 'Chocolate - White', 211, 'Outdoors', 47, false);
insert into product (id, name, price, category, stock, isdangerous) values (164, 'Extract Vanilla Pure', 851, 'Music', 21, true);
insert into product (id, name, price, category, stock, isdangerous) values (165, 'Soup - Campbells, Creamy', 416, 'Industrial', 79, true);
insert into product (id, name, price, category, stock, isdangerous) values (166, 'Cookies - Englishbay Oatmeal', 271, 'Shoes', 28, false);
insert into product (id, name, price, category, stock, isdangerous) values (167, 'Lamb Rack - Ontario', 532, 'Baby', 7, false);
insert into product (id, name, price, category, stock, isdangerous) values (168, 'Scallops - 20/30', 442, 'Home', 73, true);
insert into product (id, name, price, category, stock, isdangerous) values (169, 'Squash - Guords', 841, 'Kids', 25, false);
insert into product (id, name, price, category, stock, isdangerous) values (170, 'Mcguinness - Blue Curacao', 675, 'Home', 99, false);
insert into product (id, name, price, category, stock, isdangerous) values (171, 'Wine - Beringer Founders Estate', 474, 'Music', 32, true);
insert into product (id, name, price, category, stock, isdangerous) values (172, 'Glass - Wine, Plastic, Clear 5 Oz', 824, 'Books', 55, false);
insert into product (id, name, price, category, stock, isdangerous) values (173, 'Tia Maria', 69, 'Health', 8, true);
insert into product (id, name, price, category, stock, isdangerous) values (174, 'Lettuce - Radicchio', 122, 'Automotive', 7, true);
insert into product (id, name, price, category, stock, isdangerous) values (175, 'Paper Towel Touchless', 104, 'Computers', 98, false);
insert into product (id, name, price, category, stock, isdangerous) values (176, 'Coffee - French Vanilla Frothy', 899, 'Outdoors', 86, false);
insert into product (id, name, price, category, stock, isdangerous) values (177, 'Tart - Pecan Butter Squares', 487, 'Electronics', 98, true);
insert into product (id, name, price, category, stock, isdangerous) values (178, 'Dc Hikiage Hira Huba', 895, 'Computers', 84, false);
insert into product (id, name, price, category, stock, isdangerous) values (179, 'Nantucket - Kiwi Berry Cktl.', 996, 'Music', 36, false);
insert into product (id, name, price, category, stock, isdangerous) values (180, 'Turnip - White, Organic', 871, 'Outdoors', 63, true);
insert into product (id, name, price, category, stock, isdangerous) values (181, 'Beans - Black Bean, Preserved', 965, 'Jewelry', 76, false);
insert into product (id, name, price, category, stock, isdangerous) values (182, 'Wine - Gato Negro Cabernet', 139, 'Automotive', 62, true);
insert into product (id, name, price, category, stock, isdangerous) values (183, 'Icecream - Dstk Strw Chseck', 203, 'Shoes', 32, false);
insert into product (id, name, price, category, stock, isdangerous) values (184, 'Pepper - White, Ground', 203, 'Automotive', 62, true);
insert into product (id, name, price, category, stock, isdangerous) values (185, 'Basil - Primerba, Paste', 759, 'Outdoors', 78, false);
insert into product (id, name, price, category, stock, isdangerous) values (186, 'Kirsch - Schloss', 320, 'Automotive', 61, false);
insert into product (id, name, price, category, stock, isdangerous) values (187, 'Muffin Puck Ww Carrot', 39, 'Books', 89, true);
insert into product (id, name, price, category, stock, isdangerous) values (188, 'Beer - Mcauslan Apricot', 552, 'Movies', 34, false);
insert into product (id, name, price, category, stock, isdangerous) values (189, 'Cheese - Parmesan Grated', 229, 'Games', 94, false);
insert into product (id, name, price, category, stock, isdangerous) values (190, 'Island Oasis - Mango Daiquiri', 627, 'Movies', 34, true);
insert into product (id, name, price, category, stock, isdangerous) values (191, 'Ice Cream - Turtles Stick Bar', 788, 'Home', 80, true);
insert into product (id, name, price, category, stock, isdangerous) values (192, 'Doilies - 7, Paper', 330, 'Beauty', 43, true);
insert into product (id, name, price, category, stock, isdangerous) values (193, 'Flounder - Fresh', 435, 'Books', 26, true);
insert into product (id, name, price, category, stock, isdangerous) values (194, 'Doilies - 7, Paper', 677, 'Music', 75, true);
insert into product (id, name, price, category, stock, isdangerous) values (195, 'Wine - Vouvray Cuvee Domaine', 526, 'Music', 79, false);
insert into product (id, name, price, category, stock, isdangerous) values (196, 'Island Oasis - Ice Cream Mix', 428, 'Computers', 15, true);
insert into product (id, name, price, category, stock, isdangerous) values (197, 'Zucchini - Green', 89, 'Electronics', 13, true);
insert into product (id, name, price, category, stock, isdangerous) values (198, 'Bread - 10 Grain', 769, 'Automotive', 19, true);
insert into product (id, name, price, category, stock, isdangerous) values (199, 'Asparagus - Frozen', 854, 'Home', 57, false);
insert into product (id, name, price, category, stock, isdangerous) values (200, 'Nantucket Apple Juice', 74, 'Books', 28, true);
insert into product (id, name, price, category, stock, isdangerous) values (201, 'Beef - Baby, Liver', 190, 'Baby', 67, false);
insert into product (id, name, price, category, stock, isdangerous) values (202, 'Pike - Frozen Fillet', 191, 'Clothing', 25, false);
insert into product (id, name, price, category, stock, isdangerous) values (203, 'Soup - Campbells Chicken', 704, 'Home', 52, true);
insert into product (id, name, price, category, stock, isdangerous) values (204, 'Steel Wool S.o.s', 644, 'Books', 86, true);
insert into product (id, name, price, category, stock, isdangerous) values (205, 'Coffee - Dark Roast', 678, 'Kids', 10, true);
insert into product (id, name, price, category, stock, isdangerous) values (206, 'Corn - Cream, Canned', 685, 'Health', 67, false);
insert into product (id, name, price, category, stock, isdangerous) values (207, 'General Purpose Trigger', 441, 'Home', 88, true);
insert into product (id, name, price, category, stock, isdangerous) values (208, 'Pasta - Bauletti, Chicken White', 667, 'Games', 17, false);
insert into product (id, name, price, category, stock, isdangerous) values (209, 'Truffle Shells - White Chocolate', 897, 'Books', 21, true);
insert into product (id, name, price, category, stock, isdangerous) values (210, 'Veal - Provimi Inside', 715, 'Shoes', 15, false);
insert into product (id, name, price, category, stock, isdangerous) values (211, 'Tea - Black Currant', 355, 'Electronics', 73, false);
insert into product (id, name, price, category, stock, isdangerous) values (212, 'Bread - Granary Small Pull', 337, 'Beauty', 6, false);
insert into product (id, name, price, category, stock, isdangerous) values (213, 'Cheese - Roquefort Pappillon', 415, 'Electronics', 62, false);
insert into product (id, name, price, category, stock, isdangerous) values (214, 'Stock - Veal, White', 410, 'Grocery', 22, false);
insert into product (id, name, price, category, stock, isdangerous) values (215, 'Coffee - Colombian, Portioned', 113, 'Outdoors', 15, false);
insert into product (id, name, price, category, stock, isdangerous) values (216, 'Beef - Tenderloin', 172, 'Sports', 17, false);
insert into product (id, name, price, category, stock, isdangerous) values (217, 'Wasabi Powder', 625, 'Shoes', 80, true);
insert into product (id, name, price, category, stock, isdangerous) values (218, 'Ostrich - Prime Cut', 913, 'Books', 69, true);
insert into product (id, name, price, category, stock, isdangerous) values (219, 'Shrimp - 16/20, Peeled Deviened', 799, 'Tools', 58, true);
insert into product (id, name, price, category, stock, isdangerous) values (220, 'Pork - Bacon,back Peameal', 236, 'Games', 16, true);
insert into product (id, name, price, category, stock, isdangerous) values (221, 'Beef - Ox Tongue', 274, 'Garden', 93, false);
insert into product (id, name, price, category, stock, isdangerous) values (222, 'Energy Drink Red Bull', 254, 'Industrial', 57, true);
insert into product (id, name, price, category, stock, isdangerous) values (223, 'Wine - Fino Tio Pepe Gonzalez', 69, 'Electronics', 31, false);
insert into product (id, name, price, category, stock, isdangerous) values (224, 'Water - Mineral, Natural', 610, 'Computers', 62, false);
insert into product (id, name, price, category, stock, isdangerous) values (225, 'Kiwi Gold Zespri', 526, 'Kids', 66, true);
insert into product (id, name, price, category, stock, isdangerous) values (226, 'Cheese - Gorgonzola', 148, 'Books', 14, false);
insert into product (id, name, price, category, stock, isdangerous) values (227, 'Versatainer Nc - 8288', 51, 'Garden', 58, true);
insert into product (id, name, price, category, stock, isdangerous) values (228, 'Juice - Cranberry, 341 Ml', 257, 'Computers', 2, true);
insert into product (id, name, price, category, stock, isdangerous) values (229, 'Soup V8 Roasted Red Pepper', 146, 'Home', 77, true);
insert into product (id, name, price, category, stock, isdangerous) values (230, 'Garbage Bags - Black', 166, 'Music', 32, true);
insert into product (id, name, price, category, stock, isdangerous) values (231, 'Doilies - 8, Paper', 379, 'Jewelry', 20, false);
insert into product (id, name, price, category, stock, isdangerous) values (232, 'Quinoa', 441, 'Tools', 17, false);
insert into product (id, name, price, category, stock, isdangerous) values (233, 'Salt - Table', 458, 'Sports', 23, true);
insert into product (id, name, price, category, stock, isdangerous) values (234, 'Beer - Muskoka Cream Ale', 134, 'Shoes', 79, false);
insert into product (id, name, price, category, stock, isdangerous) values (235, 'Corn - Cream, Canned', 394, 'Movies', 30, false);
insert into product (id, name, price, category, stock, isdangerous) values (236, 'Slt - Individual Portions', 756, 'Electronics', 55, true);
insert into product (id, name, price, category, stock, isdangerous) values (237, 'Duck - Whole', 99, 'Electronics', 35, true);
insert into product (id, name, price, category, stock, isdangerous) values (238, 'Garlic - Peeled', 960, 'Books', 20, true);
insert into product (id, name, price, category, stock, isdangerous) values (239, 'Container - Hngd Cll Blk 7x7x3', 984, 'Industrial', 19, false);
insert into product (id, name, price, category, stock, isdangerous) values (240, 'Bread Sour Rolls', 377, 'Health', 86, false);
insert into product (id, name, price, category, stock, isdangerous) values (241, 'Black Currants', 307, 'Toys', 5, true);
insert into product (id, name, price, category, stock, isdangerous) values (242, 'Cheese - Cambozola', 728, 'Jewelry', 84, false);
insert into product (id, name, price, category, stock, isdangerous) values (243, 'Pepper - Pablano', 537, 'Clothing', 74, true);
insert into product (id, name, price, category, stock, isdangerous) values (244, 'Beans - Black Bean, Dry', 822, 'Electronics', 45, false);
insert into product (id, name, price, category, stock, isdangerous) values (245, 'Quail - Whole, Boneless', 511, 'Jewelry', 63, false);
insert into product (id, name, price, category, stock, isdangerous) values (246, 'Chilli Paste, Sambal Oelek', 56, 'Beauty', 32, true);
insert into product (id, name, price, category, stock, isdangerous) values (247, 'Chutney Sauce - Mango', 663, 'Music', 34, true);
insert into product (id, name, price, category, stock, isdangerous) values (248, 'Oil - Sesame', 399, 'Beauty', 13, true);
insert into product (id, name, price, category, stock, isdangerous) values (249, 'Filter - Coffee', 337, 'Jewelry', 73, false);
insert into product (id, name, price, category, stock, isdangerous) values (250, 'Pepper - Red, Finger Hot', 537, 'Kids', 95, false);
insert into product (id, name, price, category, stock, isdangerous) values (251, 'Mikes Hard Lemonade', 236, 'Industrial', 55, true);
insert into product (id, name, price, category, stock, isdangerous) values (252, 'Icecream - Dstk Strw Chseck', 783, 'Electronics', 81, true);
insert into product (id, name, price, category, stock, isdangerous) values (253, 'Sauce - Rosee', 204, 'Books', 81, false);
insert into product (id, name, price, category, stock, isdangerous) values (254, 'Clam Nectar', 387, 'Beauty', 26, true);
insert into product (id, name, price, category, stock, isdangerous) values (255, 'Wine - Red, Wolf Blass, Yellow', 972, 'Garden', 61, true);
insert into product (id, name, price, category, stock, isdangerous) values (256, 'Compound - Raspberry', 207, 'Beauty', 10, true);
insert into product (id, name, price, category, stock, isdangerous) values (257, 'Pernod', 797, 'Beauty', 9, false);
insert into product (id, name, price, category, stock, isdangerous) values (258, 'Cleaner - Comet', 550, 'Books', 33, false);
insert into product (id, name, price, category, stock, isdangerous) values (259, 'Rye Special Old', 291, 'Music', 70, false);
insert into product (id, name, price, category, stock, isdangerous) values (260, 'Crackers - Soda / Saltins', 806, 'Games', 8, false);
insert into product (id, name, price, category, stock, isdangerous) values (261, 'Coffee - Dark Roast', 672, 'Kids', 100, true);
insert into product (id, name, price, category, stock, isdangerous) values (262, 'Lobster - Tail, 3 - 4 Oz', 397, 'Health', 30, false);
insert into product (id, name, price, category, stock, isdangerous) values (263, 'Shrimp - Baby, Cold Water', 885, 'Kids', 59, true);
insert into product (id, name, price, category, stock, isdangerous) values (264, 'Lobster - Tail 6 Oz', 87, 'Tools', 16, true);
insert into product (id, name, price, category, stock, isdangerous) values (265, 'Soup V8 Roasted Red Pepper', 396, 'Books', 38, true);
insert into product (id, name, price, category, stock, isdangerous) values (266, 'Pork - Loin, Bone - In', 138, 'Beauty', 3, false);
insert into product (id, name, price, category, stock, isdangerous) values (267, 'Wine - White, Ej Gallo', 536, 'Computers', 99, false);
insert into product (id, name, price, category, stock, isdangerous) values (268, 'Bread - Raisin', 160, 'Toys', 83, false);
insert into product (id, name, price, category, stock, isdangerous) values (269, 'Energy Drink Red Bull', 850, 'Tools', 76, false);
insert into product (id, name, price, category, stock, isdangerous) values (270, 'Maple Syrup', 539, 'Electronics', 99, true);
insert into product (id, name, price, category, stock, isdangerous) values (271, 'Bread Foccacia Whole', 264, 'Music', 100, true);
insert into product (id, name, price, category, stock, isdangerous) values (272, 'Doilies - 12, Paper', 246, 'Toys', 41, false);
insert into product (id, name, price, category, stock, isdangerous) values (273, 'Pepper - Paprika, Hungarian', 303, 'Games', 54, false);
insert into product (id, name, price, category, stock, isdangerous) values (274, 'Beef - Tongue, Fresh', 730, 'Baby', 75, false);
insert into product (id, name, price, category, stock, isdangerous) values (275, 'Bread Roll Foccacia', 204, 'Clothing', 12, false);
insert into product (id, name, price, category, stock, isdangerous) values (276, 'Lettuce Romaine Chopped', 428, 'Movies', 81, false);
insert into product (id, name, price, category, stock, isdangerous) values (277, 'Beans - Soya Bean', 631, 'Games', 96, true);
insert into product (id, name, price, category, stock, isdangerous) values (278, 'Squid Ink', 546, 'Outdoors', 44, true);
insert into product (id, name, price, category, stock, isdangerous) values (279, 'Asparagus - Frozen', 228, 'Industrial', 83, false);
insert into product (id, name, price, category, stock, isdangerous) values (280, 'Lentils - Green, Dry', 409, 'Health', 66, true);
insert into product (id, name, price, category, stock, isdangerous) values (281, 'Mackerel Whole Fresh', 128, 'Computers', 96, true);
insert into product (id, name, price, category, stock, isdangerous) values (282, 'Extract - Almond', 641, 'Industrial', 74, false);
insert into product (id, name, price, category, stock, isdangerous) values (283, 'Potatoes - Yukon Gold 5 Oz', 429, 'Electronics', 36, true);
insert into product (id, name, price, category, stock, isdangerous) values (284, 'Mustard - Individual Pkg', 222, 'Grocery', 31, false);
insert into product (id, name, price, category, stock, isdangerous) values (285, 'Quinoa', 208, 'Kids', 21, false);
insert into product (id, name, price, category, stock, isdangerous) values (286, 'Longan', 302, 'Shoes', 18, false);
insert into product (id, name, price, category, stock, isdangerous) values (287, 'Tea - Herbal Orange Spice', 723, 'Music', 94, false);
insert into product (id, name, price, category, stock, isdangerous) values (288, 'Pork - Back, Short Cut, Boneless', 342, 'Beauty', 39, true);
insert into product (id, name, price, category, stock, isdangerous) values (289, 'Egg Patty Fried', 887, 'Clothing', 90, false);
insert into product (id, name, price, category, stock, isdangerous) values (290, 'Mousse - Passion Fruit', 40, 'Industrial', 10, false);
insert into product (id, name, price, category, stock, isdangerous) values (291, 'Cake Circle, Foil, Scallop', 304, 'Games', 83, false);
insert into product (id, name, price, category, stock, isdangerous) values (292, 'Mushroom - Chanterelle, Dry', 787, 'Grocery', 5, false);
insert into product (id, name, price, category, stock, isdangerous) values (293, 'Bread - Crumbs, Bulk', 959, 'Computers', 58, true);
insert into product (id, name, price, category, stock, isdangerous) values (294, 'Apple - Royal Gala', 105, 'Jewelry', 48, false);
insert into product (id, name, price, category, stock, isdangerous) values (295, 'Gherkin', 724, 'Jewelry', 100, true);
insert into product (id, name, price, category, stock, isdangerous) values (296, 'Nut - Pumpkin Seeds', 921, 'Garden', 18, false);
insert into product (id, name, price, category, stock, isdangerous) values (297, 'Flower - Leather Leaf Fern', 973, 'Home', 72, true);
insert into product (id, name, price, category, stock, isdangerous) values (298, 'Jam - Raspberry', 144, 'Outdoors', 40, false);
insert into product (id, name, price, category, stock, isdangerous) values (299, 'Crab - Soft Shell', 64, 'Garden', 45, true);
insert into product (id, name, price, category, stock, isdangerous) values (300, 'Tomatoes Tear Drop', 341, 'Industrial', 72, true);
insert into product (id, name, price, category, stock, isdangerous) values (301, 'Pepper - Jalapeno', 738, 'Outdoors', 28, false);
insert into product (id, name, price, category, stock, isdangerous) values (302, 'Brandy Apricot', 401, 'Baby', 74, true);
insert into product (id, name, price, category, stock, isdangerous) values (303, 'Mousse - Passion Fruit', 778, 'Books', 62, false);
insert into product (id, name, price, category, stock, isdangerous) values (304, 'Beer - Tetleys', 663, 'Movies', 72, false);
insert into product (id, name, price, category, stock, isdangerous) values (305, 'Port - 74 Brights', 954, 'Toys', 91, true);
insert into product (id, name, price, category, stock, isdangerous) values (306, 'Pasta - Cheese / Spinach Bauletti', 444, 'Tools', 86, true);
insert into product (id, name, price, category, stock, isdangerous) values (307, 'Tart Shells - Sweet, 4', 684, 'Home', 76, true);
insert into product (id, name, price, category, stock, isdangerous) values (308, 'Clams - Littleneck, Whole', 601, 'Clothing', 19, true);
insert into product (id, name, price, category, stock, isdangerous) values (309, 'Apple - Delicious, Red', 369, 'Shoes', 82, true);
insert into product (id, name, price, category, stock, isdangerous) values (310, 'Onion Powder', 929, 'Electronics', 91, false);
insert into product (id, name, price, category, stock, isdangerous) values (311, 'Wine - Pinot Grigio Collavini', 510, 'Health', 13, false);
insert into product (id, name, price, category, stock, isdangerous) values (312, 'Buffalo - Short Rib Fresh', 953, 'Shoes', 24, false);
insert into product (id, name, price, category, stock, isdangerous) values (313, 'Sterno - Chafing Dish Fuel', 883, 'Tools', 92, false);
insert into product (id, name, price, category, stock, isdangerous) values (314, 'Cheese - Brie, Triple Creme', 90, 'Tools', 3, true);
insert into product (id, name, price, category, stock, isdangerous) values (315, 'Muffin Hinge 117n', 74, 'Music', 34, false);
insert into product (id, name, price, category, stock, isdangerous) values (316, 'Sesame Seed Black', 720, 'Industrial', 21, false);
insert into product (id, name, price, category, stock, isdangerous) values (317, 'Artichoke - Hearts, Canned', 917, 'Automotive', 14, true);
insert into product (id, name, price, category, stock, isdangerous) values (318, 'Sambuca - Ramazzotti', 91, 'Computers', 87, false);
insert into product (id, name, price, category, stock, isdangerous) values (319, 'Snapple Lemon Tea', 750, 'Industrial', 35, false);
insert into product (id, name, price, category, stock, isdangerous) values (320, 'Container - Foam Dixie 12 Oz', 695, 'Electronics', 86, false);
insert into product (id, name, price, category, stock, isdangerous) values (321, 'Peas - Pigeon, Dry', 634, 'Grocery', 26, true);
insert into product (id, name, price, category, stock, isdangerous) values (322, 'Kohlrabi', 40, 'Games', 77, true);
insert into product (id, name, price, category, stock, isdangerous) values (323, 'Veal - Brisket, Provimi,bnls', 736, 'Baby', 43, false);
insert into product (id, name, price, category, stock, isdangerous) values (324, 'Appetizer - Spring Roll, Veg', 142, 'Tools', 12, false);
insert into product (id, name, price, category, stock, isdangerous) values (325, 'Dried Cranberries', 462, 'Shoes', 50, false);
insert into product (id, name, price, category, stock, isdangerous) values (326, 'Wine - Chardonnay Mondavi', 389, 'Tools', 23, true);
insert into product (id, name, price, category, stock, isdangerous) values (327, 'Wine - Vovray Sec Domaine Huet', 932, 'Home', 21, true);
insert into product (id, name, price, category, stock, isdangerous) values (328, 'Cape Capensis - Fillet', 691, 'Jewelry', 89, false);
insert into product (id, name, price, category, stock, isdangerous) values (329, 'Salmon Atl.whole 8 - 10 Lb', 770, 'Computers', 31, false);
insert into product (id, name, price, category, stock, isdangerous) values (330, 'Baking Powder', 190, 'Movies', 52, true);
insert into product (id, name, price, category, stock, isdangerous) values (331, 'Wine - Blue Nun Qualitatswein', 751, 'Shoes', 28, false);
insert into product (id, name, price, category, stock, isdangerous) values (332, 'Bag Clear 10 Lb', 688, 'Music', 31, false);
insert into product (id, name, price, category, stock, isdangerous) values (333, 'Banana - Green', 739, 'Beauty', 78, true);
insert into product (id, name, price, category, stock, isdangerous) values (334, 'Chocolate - Dark Callets', 803, 'Beauty', 84, true);
insert into product (id, name, price, category, stock, isdangerous) values (335, 'Chicken - Wieners', 433, 'Home', 24, true);
insert into product (id, name, price, category, stock, isdangerous) values (336, 'Soup - Base Broth Beef', 431, 'Home', 60, false);
insert into product (id, name, price, category, stock, isdangerous) values (337, 'Taro Leaves', 247, 'Games', 24, false);
insert into product (id, name, price, category, stock, isdangerous) values (338, 'Honey - Lavender', 354, 'Health', 54, true);
insert into product (id, name, price, category, stock, isdangerous) values (339, 'Broccoli - Fresh', 202, 'Garden', 71, false);
insert into product (id, name, price, category, stock, isdangerous) values (340, 'Juice - Grape, White', 120, 'Home', 53, false);
insert into product (id, name, price, category, stock, isdangerous) values (341, 'Cake - Night And Day Choclate', 325, 'Toys', 61, false);
insert into product (id, name, price, category, stock, isdangerous) values (342, 'Pate - Peppercorn', 841, 'Computers', 54, true);
insert into product (id, name, price, category, stock, isdangerous) values (343, 'Sauerkraut', 196, 'Industrial', 28, false);
insert into product (id, name, price, category, stock, isdangerous) values (344, 'Cognac - Courvaisier', 210, 'Tools', 91, false);
insert into product (id, name, price, category, stock, isdangerous) values (345, 'Tomatoes Tear Drop', 822, 'Health', 63, false);
insert into product (id, name, price, category, stock, isdangerous) values (346, 'Cheese - Brick With Onion', 780, 'Electronics', 21, false);
insert into product (id, name, price, category, stock, isdangerous) values (347, 'Salt - Kosher', 436, 'Sports', 27, false);
insert into product (id, name, price, category, stock, isdangerous) values (348, 'Shiratamako - Rice Flour', 652, 'Health', 60, true);
insert into product (id, name, price, category, stock, isdangerous) values (349, 'Tea - Apple Green Tea', 498, 'Shoes', 11, true);
insert into product (id, name, price, category, stock, isdangerous) values (350, 'Cheese - Swiss', 124, 'Automotive', 87, false);
insert into product (id, name, price, category, stock, isdangerous) values (351, 'Lettuce - Spring Mix', 993, 'Outdoors', 1, true);
insert into product (id, name, price, category, stock, isdangerous) values (352, 'Raspberries - Fresh', 741, 'Beauty', 67, false);
insert into product (id, name, price, category, stock, isdangerous) values (353, 'Peas - Pigeon, Dry', 632, 'Home', 9, false);
insert into product (id, name, price, category, stock, isdangerous) values (354, 'Turkey - Breast, Boneless Sk On', 432, 'Books', 91, false);
insert into product (id, name, price, category, stock, isdangerous) values (355, 'Cookies Oatmeal Raisin', 656, 'Games', 37, true);
insert into product (id, name, price, category, stock, isdangerous) values (356, 'Juice - Orange 1.89l', 165, 'Grocery', 49, true);
insert into product (id, name, price, category, stock, isdangerous) values (357, 'Pop Shoppe Cream Soda', 660, 'Electronics', 9, true);
insert into product (id, name, price, category, stock, isdangerous) values (358, 'Trout - Hot Smkd, Dbl Fillet', 183, 'Clothing', 82, false);
insert into product (id, name, price, category, stock, isdangerous) values (359, 'Yams', 982, 'Jewelry', 84, true);
insert into product (id, name, price, category, stock, isdangerous) values (360, 'Coffee Caramel Biscotti', 32, 'Baby', 63, false);
insert into product (id, name, price, category, stock, isdangerous) values (361, 'Basil - Primerba, Paste', 484, 'Toys', 32, true);
insert into product (id, name, price, category, stock, isdangerous) values (362, 'Wine - Beaujolais Villages', 922, 'Industrial', 75, true);
insert into product (id, name, price, category, stock, isdangerous) values (363, 'Cabbage - Red', 611, 'Jewelry', 56, false);
insert into product (id, name, price, category, stock, isdangerous) values (364, 'Bread - Italian Roll With Herbs', 340, 'Games', 60, false);
insert into product (id, name, price, category, stock, isdangerous) values (365, 'Pie Pecan', 761, 'Tools', 82, true);
insert into product (id, name, price, category, stock, isdangerous) values (366, 'Cleaner - Bleach', 406, 'Industrial', 71, false);
insert into product (id, name, price, category, stock, isdangerous) values (367, 'Veal - Nuckle', 515, 'Baby', 27, false);
insert into product (id, name, price, category, stock, isdangerous) values (368, 'Rhubarb', 188, 'Sports', 100, true);
insert into product (id, name, price, category, stock, isdangerous) values (369, 'Tamarind Paste', 596, 'Grocery', 78, false);
insert into product (id, name, price, category, stock, isdangerous) values (370, 'Cheese - Gorgonzola', 782, 'Automotive', 3, false);
insert into product (id, name, price, category, stock, isdangerous) values (371, 'V8 - Tropical Blend', 616, 'Industrial', 50, true);
insert into product (id, name, price, category, stock, isdangerous) values (372, 'Cabbage - Savoy', 764, 'Grocery', 76, true);
insert into product (id, name, price, category, stock, isdangerous) values (373, 'Venison - Striploin', 809, 'Games', 1, false);
insert into product (id, name, price, category, stock, isdangerous) values (374, 'The Pop Shoppe - Cream Soda', 945, 'Industrial', 23, true);
insert into product (id, name, price, category, stock, isdangerous) values (375, 'Sauce - Marinara', 960, 'Games', 45, false);
insert into product (id, name, price, category, stock, isdangerous) values (376, 'Olives - Green, Pitted', 871, 'Tools', 6, false);
insert into product (id, name, price, category, stock, isdangerous) values (377, 'Crab - Meat', 764, 'Sports', 31, true);
insert into product (id, name, price, category, stock, isdangerous) values (378, 'Cheese - Ermite Bleu', 486, 'Tools', 95, false);
insert into product (id, name, price, category, stock, isdangerous) values (379, 'Lettuce - Radicchio', 702, 'Tools', 84, false);
insert into product (id, name, price, category, stock, isdangerous) values (380, 'Mix - Cocktail Ice Cream', 68, 'Books', 89, false);
insert into product (id, name, price, category, stock, isdangerous) values (381, 'Apricots - Dried', 280, 'Jewelry', 72, true);
insert into product (id, name, price, category, stock, isdangerous) values (382, 'Ham - Procutinni', 527, 'Automotive', 33, false);
insert into product (id, name, price, category, stock, isdangerous) values (383, 'Nori Sea Weed - Gold Label', 556, 'Shoes', 42, false);
insert into product (id, name, price, category, stock, isdangerous) values (384, 'Cookies Cereal Nut', 971, 'Movies', 76, true);
insert into product (id, name, price, category, stock, isdangerous) values (385, 'Pimento - Canned', 31, 'Garden', 3, true);
insert into product (id, name, price, category, stock, isdangerous) values (386, 'Beef - Ground Medium', 856, 'Jewelry', 82, true);
insert into product (id, name, price, category, stock, isdangerous) values (387, 'Eggwhite Frozen', 826, 'Clothing', 77, false);
insert into product (id, name, price, category, stock, isdangerous) values (388, 'Propel Sport Drink', 681, 'Sports', 61, false);
insert into product (id, name, price, category, stock, isdangerous) values (389, 'Cheese - Cheddar With Claret', 432, 'Automotive', 60, true);
insert into product (id, name, price, category, stock, isdangerous) values (390, 'Soup - Campbells, Cream Of', 74, 'Automotive', 4, false);
insert into product (id, name, price, category, stock, isdangerous) values (391, 'Hipnotiq Liquor', 392, 'Jewelry', 47, true);
insert into product (id, name, price, category, stock, isdangerous) values (392, 'Stock - Veal, White', 373, 'Games', 79, false);
insert into product (id, name, price, category, stock, isdangerous) values (393, 'Yeast - Fresh, Fleischman', 559, 'Outdoors', 85, true);
insert into product (id, name, price, category, stock, isdangerous) values (394, 'Bread - Granary Small Pull', 211, 'Books', 8, true);
insert into product (id, name, price, category, stock, isdangerous) values (395, 'Wine - White, Ej', 732, 'Shoes', 49, true);
insert into product (id, name, price, category, stock, isdangerous) values (396, 'Squid - U - 10 Thailand', 586, 'Clothing', 100, false);
insert into product (id, name, price, category, stock, isdangerous) values (397, 'Mushroom - Enoki, Dry', 935, 'Computers', 25, true);
insert into product (id, name, price, category, stock, isdangerous) values (398, 'Mousse - Passion Fruit', 947, 'Garden', 26, true);
insert into product (id, name, price, category, stock, isdangerous) values (399, 'Beans - Kidney, Canned', 580, 'Beauty', 97, true);
insert into product (id, name, price, category, stock, isdangerous) values (400, 'Quail - Whole, Bone - In', 274, 'Garden', 73, false);
insert into product (id, name, price, category, stock, isdangerous) values (401, 'Wine - Pinot Grigio Collavini', 309, 'Electronics', 13, true);
insert into product (id, name, price, category, stock, isdangerous) values (402, 'Molasses - Fancy', 371, 'Music', 25, false);
insert into product (id, name, price, category, stock, isdangerous) values (403, 'Gatorade - Cool Blue Raspberry', 182, 'Movies', 56, false);
insert into product (id, name, price, category, stock, isdangerous) values (404, 'Lettuce - Sea / Sea Asparagus', 665, 'Grocery', 95, false);
insert into product (id, name, price, category, stock, isdangerous) values (405, 'Garbag Bags - Black', 117, 'Garden', 96, true);
insert into product (id, name, price, category, stock, isdangerous) values (406, 'Beef - Rib Roast, Cap On', 253, 'Grocery', 23, true);
insert into product (id, name, price, category, stock, isdangerous) values (407, 'Wine - Merlot Vina Carmen', 178, 'Music', 50, true);
insert into product (id, name, price, category, stock, isdangerous) values (408, 'Bread - Olive', 847, 'Health', 49, false);
insert into product (id, name, price, category, stock, isdangerous) values (409, 'Sauce - Hp', 84, 'Books', 65, true);
insert into product (id, name, price, category, stock, isdangerous) values (410, 'White Baguette', 475, 'Games', 92, true);
insert into product (id, name, price, category, stock, isdangerous) values (411, 'Lettuce - Boston Bib', 726, 'Kids', 81, true);
insert into product (id, name, price, category, stock, isdangerous) values (412, 'Gherkin', 36, 'Movies', 63, true);
insert into product (id, name, price, category, stock, isdangerous) values (413, 'Coffee - Beans, Whole', 816, 'Shoes', 100, true);
insert into product (id, name, price, category, stock, isdangerous) values (414, 'Cookies - Englishbay Wht', 75, 'Outdoors', 97, false);
insert into product (id, name, price, category, stock, isdangerous) values (415, 'Cheese Cloth No 100', 179, 'Toys', 68, true);
insert into product (id, name, price, category, stock, isdangerous) values (416, 'Gloves - Goldtouch Disposable', 757, 'Books', 1, false);
insert into product (id, name, price, category, stock, isdangerous) values (417, 'Spoon - Soup, Plastic', 961, 'Computers', 46, true);
insert into product (id, name, price, category, stock, isdangerous) values (418, 'Salmon - Atlantic, Fresh, Whole', 536, 'Books', 7, true);
insert into product (id, name, price, category, stock, isdangerous) values (419, 'Veal - Shank, Pieces', 977, 'Movies', 53, false);
insert into product (id, name, price, category, stock, isdangerous) values (420, 'Champagne - Brights, Dry', 241, 'Computers', 31, false);
insert into product (id, name, price, category, stock, isdangerous) values (421, 'Pepsi - 600ml', 78, 'Beauty', 5, true);
insert into product (id, name, price, category, stock, isdangerous) values (422, 'Shallots', 635, 'Clothing', 82, false);
insert into product (id, name, price, category, stock, isdangerous) values (423, 'Beans - Yellow', 541, 'Electronics', 59, false);
insert into product (id, name, price, category, stock, isdangerous) values (424, 'Filling - Mince Meat', 40, 'Tools', 34, false);
insert into product (id, name, price, category, stock, isdangerous) values (425, 'Blueberries', 726, 'Movies', 48, false);
insert into product (id, name, price, category, stock, isdangerous) values (426, 'Garbag Bags - Black', 473, 'Sports', 40, false);
insert into product (id, name, price, category, stock, isdangerous) values (427, 'Fish - Bones', 129, 'Health', 31, false);
insert into product (id, name, price, category, stock, isdangerous) values (428, 'Vodka - Smirnoff', 678, 'Computers', 88, true);
insert into product (id, name, price, category, stock, isdangerous) values (429, 'Broccoli - Fresh', 651, 'Kids', 53, false);
insert into product (id, name, price, category, stock, isdangerous) values (430, 'Fish - Bones', 487, 'Computers', 71, true);
insert into product (id, name, price, category, stock, isdangerous) values (431, 'Pork - Bacon, Sliced', 566, 'Grocery', 44, true);
insert into product (id, name, price, category, stock, isdangerous) values (432, 'Beer - Steamwhistle', 272, 'Tools', 24, false);
insert into product (id, name, price, category, stock, isdangerous) values (433, 'Tilapia - Fillets', 929, 'Music', 69, true);
insert into product (id, name, price, category, stock, isdangerous) values (434, 'Waffle Stix', 206, 'Computers', 52, false);
insert into product (id, name, price, category, stock, isdangerous) values (435, 'Lobster - Tail 6 Oz', 181, 'Jewelry', 54, false);
insert into product (id, name, price, category, stock, isdangerous) values (436, 'Shrimp - Black Tiger 16/20', 172, 'Tools', 66, false);
insert into product (id, name, price, category, stock, isdangerous) values (437, 'Jam - Blackberry, 20 Ml Jar', 724, 'Jewelry', 11, true);
insert into product (id, name, price, category, stock, isdangerous) values (438, 'Beans - Kidney, Canned', 565, 'Baby', 4, true);
insert into product (id, name, price, category, stock, isdangerous) values (439, 'Lighter - Bbq', 595, 'Games', 2, true);
insert into product (id, name, price, category, stock, isdangerous) values (440, 'Water - Mineral, Natural', 406, 'Shoes', 15, false);
insert into product (id, name, price, category, stock, isdangerous) values (441, 'Cookie Dough - Chunky', 824, 'Jewelry', 14, false);
insert into product (id, name, price, category, stock, isdangerous) values (442, 'Rice - Aborio', 560, 'Toys', 96, false);
insert into product (id, name, price, category, stock, isdangerous) values (443, 'V8 Pet', 902, 'Jewelry', 26, true);
insert into product (id, name, price, category, stock, isdangerous) values (444, 'Lettuce - Boston Bib - Organic', 259, 'Jewelry', 13, false);
insert into product (id, name, price, category, stock, isdangerous) values (445, 'Nectarines', 599, 'Tools', 46, true);
insert into product (id, name, price, category, stock, isdangerous) values (446, 'Muffin Carrot - Individual', 188, 'Tools', 6, false);
insert into product (id, name, price, category, stock, isdangerous) values (447, 'Alize Gold Passion', 172, 'Outdoors', 58, true);
insert into product (id, name, price, category, stock, isdangerous) values (448, 'Tofu - Soft', 122, 'Shoes', 56, true);
insert into product (id, name, price, category, stock, isdangerous) values (449, 'Bacardi Mojito', 854, 'Clothing', 59, false);
insert into product (id, name, price, category, stock, isdangerous) values (450, 'Lobster - Base', 63, 'Garden', 36, false);
insert into product (id, name, price, category, stock, isdangerous) values (451, 'Wine - Red, Black Opal Shiraz', 928, 'Shoes', 34, false);
insert into product (id, name, price, category, stock, isdangerous) values (452, 'Creamers - 10%', 450, 'Computers', 63, true);
insert into product (id, name, price, category, stock, isdangerous) values (453, 'Celery Root', 326, 'Movies', 38, false);
insert into product (id, name, price, category, stock, isdangerous) values (454, 'Beans - Turtle, Black, Dry', 933, 'Outdoors', 27, false);
insert into product (id, name, price, category, stock, isdangerous) values (455, 'Pasta - Linguini, Dry', 935, 'Games', 85, true);
insert into product (id, name, price, category, stock, isdangerous) values (456, 'Lambcasing', 647, 'Music', 31, false);
insert into product (id, name, price, category, stock, isdangerous) values (457, 'Flour - Semolina', 664, 'Outdoors', 62, false);
insert into product (id, name, price, category, stock, isdangerous) values (458, 'Wakami Seaweed', 174, 'Sports', 62, false);
insert into product (id, name, price, category, stock, isdangerous) values (459, 'Onions - Cooking', 405, 'Electronics', 79, false);
insert into product (id, name, price, category, stock, isdangerous) values (460, 'Mushroom - Portebello', 203, 'Shoes', 99, true);
insert into product (id, name, price, category, stock, isdangerous) values (461, 'Bread Roll Foccacia', 832, 'Computers', 75, true);
insert into product (id, name, price, category, stock, isdangerous) values (462, 'Milk - 2% 250 Ml', 330, 'Sports', 76, true);
insert into product (id, name, price, category, stock, isdangerous) values (463, 'Tomatoes - Vine Ripe, Red', 307, 'Garden', 50, false);
insert into product (id, name, price, category, stock, isdangerous) values (464, 'Salsify, Organic', 135, 'Outdoors', 61, true);
insert into product (id, name, price, category, stock, isdangerous) values (465, 'Beer - Pilsner Urquell', 89, 'Beauty', 1, true);
insert into product (id, name, price, category, stock, isdangerous) values (466, 'Kiwano', 344, 'Jewelry', 80, true);
insert into product (id, name, price, category, stock, isdangerous) values (467, 'Stock - Beef, White', 623, 'Books', 87, true);
insert into product (id, name, price, category, stock, isdangerous) values (468, 'Soup - Campbells, Chix Gumbo', 721, 'Automotive', 10, false);
insert into product (id, name, price, category, stock, isdangerous) values (469, 'Piping Jelly - All Colours', 258, 'Kids', 25, true);
insert into product (id, name, price, category, stock, isdangerous) values (470, 'Lentils - Red, Dry', 875, 'Kids', 99, true);
insert into product (id, name, price, category, stock, isdangerous) values (471, 'Tomato Puree', 836, 'Tools', 96, true);
insert into product (id, name, price, category, stock, isdangerous) values (472, 'Cheese - Romano, Grated', 734, 'Baby', 64, true);
insert into product (id, name, price, category, stock, isdangerous) values (473, 'Apple - Custard', 60, 'Sports', 44, true);
insert into product (id, name, price, category, stock, isdangerous) values (474, 'Bag Clear 10 Lb', 305, 'Beauty', 91, false);
insert into product (id, name, price, category, stock, isdangerous) values (475, 'Jolt Cola - Electric Blue', 999, 'Music', 49, true);
insert into product (id, name, price, category, stock, isdangerous) values (476, 'Yams', 836, 'Automotive', 70, true);
insert into product (id, name, price, category, stock, isdangerous) values (477, 'Flour - Strong', 730, 'Garden', 85, false);
insert into product (id, name, price, category, stock, isdangerous) values (478, 'Beans - Navy, Dry', 379, 'Sports', 49, true);
insert into product (id, name, price, category, stock, isdangerous) values (479, 'Plums - Red', 398, 'Jewelry', 51, false);
insert into product (id, name, price, category, stock, isdangerous) values (480, 'Vinegar - Raspberry', 778, 'Baby', 85, false);
insert into product (id, name, price, category, stock, isdangerous) values (481, 'Sprouts - Peppercress', 227, 'Health', 1, true);
insert into product (id, name, price, category, stock, isdangerous) values (482, 'Red Pepper Paste', 464, 'Movies', 100, false);
insert into product (id, name, price, category, stock, isdangerous) values (483, 'Cup - 4oz Translucent', 125, 'Movies', 61, false);
insert into product (id, name, price, category, stock, isdangerous) values (484, 'Lemonade - Strawberry, 591 Ml', 409, 'Music', 97, false);
insert into product (id, name, price, category, stock, isdangerous) values (485, 'Sugar Thermometer', 850, 'Outdoors', 15, true);
insert into product (id, name, price, category, stock, isdangerous) values (486, 'Pail - 4l White, With Handle', 44, 'Garden', 30, true);
insert into product (id, name, price, category, stock, isdangerous) values (487, 'Wine - Valpolicella Masi', 72, 'Computers', 44, true);
insert into product (id, name, price, category, stock, isdangerous) values (488, 'Cheese - Romano, Grated', 880, 'Shoes', 60, false);
insert into product (id, name, price, category, stock, isdangerous) values (489, 'Clams - Littleneck, Whole', 669, 'Computers', 18, true);
insert into product (id, name, price, category, stock, isdangerous) values (490, 'Bread - Crusty Italian Poly', 321, 'Industrial', 98, true);
insert into product (id, name, price, category, stock, isdangerous) values (491, 'Rabbit - Whole', 637, 'Games', 100, false);
insert into product (id, name, price, category, stock, isdangerous) values (492, 'Wine - Prem Select Charddonany', 283, 'Home', 33, true);
insert into product (id, name, price, category, stock, isdangerous) values (493, 'Vinegar - White Wine', 613, 'Outdoors', 25, false);
insert into product (id, name, price, category, stock, isdangerous) values (494, 'Momiji Oroshi Chili Sauce', 211, 'Books', 22, false);
insert into product (id, name, price, category, stock, isdangerous) values (495, 'Sage - Fresh', 401, 'Movies', 73, true);
insert into product (id, name, price, category, stock, isdangerous) values (496, 'Pork - Suckling Pig', 247, 'Music', 92, true);
insert into product (id, name, price, category, stock, isdangerous) values (497, 'Placemat - Scallop, White', 896, 'Music', 48, false);
insert into product (id, name, price, category, stock, isdangerous) values (498, 'Cucumber - English', 467, 'Clothing', 13, true);
insert into product (id, name, price, category, stock, isdangerous) values (499, 'Hot Choc Vending', 115, 'Garden', 81, true);
insert into product (id, name, price, category, stock, isdangerous) values (500, 'Juice - Mango', 393, 'Garden', 37, true);
